// Code generated by scripts/gen_entities.py from schemas.json. DO NOT EDIT.

package masterdata

// EntityMBattle is table key "m_battle".
type EntityMBattle struct {
	_                   struct{} `msgpack:",array"`
	BattleId            int32
	BattleNpcId         int64
	DeckType            int32
	BattleNpcDeckNumber int32
}

// EntityMBattleDropReward is table key "m_battle_drop_reward".
type EntityMBattleDropReward struct {
	_                  struct{} `msgpack:",array"`
	BattleDropRewardId int32
	PossessionType     int32
	PossessionId       int32
	Count              int32
}

// EntityMBattleGroup is table key "m_battle_group".
type EntityMBattleGroup struct {
	_                             struct{} `msgpack:",array"`
	BattleGroupId                 int32
	WaveNumber                    int32
	BattleId                      int32
	WaveStartActAssetId           int32
	WaveEndActAssetId             int32
	BattleCameraControllerAssetId int32
	BattlePointIndex              int32
	BattleStartCameraType         int32
}

// EntityMBattleNpcDeck is table key "m_battle_npc_deck".
type EntityMBattleNpcDeck struct {
	_                            struct{} `msgpack:",array"`
	BattleNpcId                  int64
	DeckType                     int32
	BattleNpcDeckNumber          int32
	BattleNpcDeckCharacterUuid01 string
	BattleNpcDeckCharacterUuid02 string
	BattleNpcDeckCharacterUuid03 string
	Name                         string
	Power                        int32
}

// EntityMBattleNpcDeckCharacterDropCategory is table key "m_battle_npc_deck_character_drop_category".
type EntityMBattleNpcDeckCharacterDropCategory struct {
	_                          struct{} `msgpack:",array"`
	BattleNpcId                int64
	BattleNpcDeckCharacterUuid string
	BattleDropCategoryId       int32
}

// EntityMBattleRentalDeck is table key "m_battle_rental_deck".
type EntityMBattleRentalDeck struct {
	_                   struct{} `msgpack:",array"`
	BattleGroupId       int32
	BattleNpcId         int64
	DeckType            int32
	BattleNpcDeckNumber int32
}

// EntityMBigHuntBoss is table key "m_big_hunt_boss".
type EntityMBigHuntBoss struct {
	_                       struct{} `msgpack:",array"`
	BigHuntBossId           int32
	BigHuntBossGradeGroupId int32
	NameBigHuntBossTextId   int32
	BigHuntBossAssetId      int32
	AttributeType           int32
}

// EntityMBigHuntBossGradeGroup is table key "m_big_hunt_boss_grade_group".
type EntityMBigHuntBossGradeGroup struct {
	_                       struct{} `msgpack:",array"`
	BigHuntBossGradeGroupId int32
	NecessaryScore          int64
	AssetGradeIconId        int32
}

// EntityMBigHuntBossQuest is table key "m_big_hunt_boss_quest".
type EntityMBigHuntBossQuest struct {
	_                                  struct{} `msgpack:",array"`
	BigHuntBossQuestId                 int32
	BigHuntBossId                      int32
	BigHuntQuestGroupId                int32
	BigHuntBossQuestScoreCoefficientId int32
	BigHuntScoreRewardGroupScheduleId  int32
	BigHuntLinkId                      int32
	DailyChallengeCount                int32
}

// EntityMBigHuntQuest is table key "m_big_hunt_quest".
type EntityMBigHuntQuest struct {
	_                              struct{} `msgpack:",array"`
	BigHuntQuestId                 int32
	QuestId                        int32
	BigHuntQuestScoreCoefficientId int32
}

// EntityMBigHuntQuestScoreCoefficient is table key "m_big_hunt_quest_score_coefficient".
type EntityMBigHuntQuestScoreCoefficient struct {
	_                              struct{} `msgpack:",array"`
	BigHuntQuestScoreCoefficientId int32
	ScoreDifficultBonusPermil      int32
}

// EntityMBigHuntRewardGroup is table key "m_big_hunt_reward_group".
type EntityMBigHuntRewardGroup struct {
	_                    struct{} `msgpack:",array"`
	BigHuntRewardGroupId int32
	SortOrder            int32
	PossessionType       int32
	PossessionId         int32
	Count                int32
}

// EntityMBigHuntSchedule is table key "m_big_hunt_schedule".
type EntityMBigHuntSchedule struct {
	_                      struct{} `msgpack:",array"`
	BigHuntScheduleId      int32
	NoticeStartDatetime    int64
	ChallengeStartDatetime int64
	ChallengeEndDatetime   int64
	SeasonAssetId          int32
}

// EntityMBigHuntScoreRewardGroup is table key "m_big_hunt_score_reward_group".
type EntityMBigHuntScoreRewardGroup struct {
	_                         struct{} `msgpack:",array"`
	BigHuntScoreRewardGroupId int32
	NecessaryScore            int64
	BigHuntRewardGroupId      int32
}

// EntityMBigHuntScoreRewardGroupSchedule is table key "m_big_hunt_score_reward_group_schedule".
type EntityMBigHuntScoreRewardGroupSchedule struct {
	_                                 struct{} `msgpack:",array"`
	BigHuntScoreRewardGroupScheduleId int32
	GroupIndex                        int32
	BigHuntScoreRewardGroupId         int32
	StartDatetime                     int64
}

// EntityMBigHuntWeeklyAttributeScoreRewardGroupSchedule is table key "m_big_hunt_weekly_attribute_score_reward_group_schedule".
type EntityMBigHuntWeeklyAttributeScoreRewardGroupSchedule struct {
	_                                                struct{} `msgpack:",array"`
	BigHuntWeeklyAttributeScoreRewardGroupScheduleId int32
	AttributeType                                    int32
	GroupIndex                                       int32
	BigHuntScoreRewardGroupId                        int32
	StartDatetime                                    int64
}

// EntityMCageOrnament is table key "m_cage_ornament".
type EntityMCageOrnament struct {
	_                    struct{} `msgpack:",array"`
	CageOrnamentId       int32
	StartDatetime        int64
	EndDatetime          int64
	CageOrnamentRewardId int32
}

// EntityMCageOrnamentReward is table key "m_cage_ornament_reward".
type EntityMCageOrnamentReward struct {
	_                    struct{} `msgpack:",array"`
	CageOrnamentRewardId int32
	PossessionType       int32
	PossessionId         int32
	Count                int32
}

// EntityMCatalogCostume is table key "m_catalog_costume".
type EntityMCatalogCostume struct {
	_             struct{} `msgpack:",array"`
	CostumeId     int32
	SortOrder     int32
	CatalogTermId int32
}

// EntityMCatalogWeapon is table key "m_catalog_weapon".
type EntityMCatalogWeapon struct {
	_             struct{} `msgpack:",array"`
	WeaponId      int32
	SortOrder     int32
	CatalogTermId int32
}

// EntityMCharacterBoard is table key "m_character_board".
type EntityMCharacterBoard struct {
	_                                    struct{} `msgpack:",array"`
	CharacterBoardId                     int32
	CharacterBoardGroupId                int32
	CharacterBoardUnlockConditionGroupId int32
	ReleaseRank                          int32
}

// EntityMCharacterBoardAbility is table key "m_character_board_ability".
type EntityMCharacterBoardAbility struct {
	_                                 struct{} `msgpack:",array"`
	CharacterBoardAbilityId           int32
	CharacterBoardEffectTargetGroupId int32
	AbilityId                         int32
}

// EntityMCharacterBoardAbilityMaxLevel is table key "m_character_board_ability_max_level".
type EntityMCharacterBoardAbilityMaxLevel struct {
	_           struct{} `msgpack:",array"`
	CharacterId int32
	AbilityId   int32
	MaxLevel    int32
}

// EntityMCharacterBoardEffectTargetGroup is table key "m_character_board_effect_target_group".
type EntityMCharacterBoardEffectTargetGroup struct {
	_                                 struct{} `msgpack:",array"`
	CharacterBoardEffectTargetGroupId int32
	GroupIndex                        int32
	CharacterBoardEffectTargetType    int32
	TargetValue                       int32
}

// EntityMCharacterBoardPanel is table key "m_character_board_panel".
type EntityMCharacterBoardPanel struct {
	_                                           struct{} `msgpack:",array"`
	CharacterBoardPanelId                       int32
	CharacterBoardId                            int32
	CharacterBoardPanelUnlockConditionGroupId   int32
	CharacterBoardPanelReleasePossessionGroupId int32
	CharacterBoardPanelReleaseRewardGroupId     int32
	CharacterBoardPanelReleaseEffectGroupId     int32
	SortOrder                                   int32
	ParentCharacterBoardPanelId                 int32
	PlaceIndex                                  int32
}

// EntityMCharacterBoardPanelReleaseEffectGroup is table key "m_character_board_panel_release_effect_group".
type EntityMCharacterBoardPanelReleaseEffectGroup struct {
	_                                       struct{} `msgpack:",array"`
	CharacterBoardPanelReleaseEffectGroupId int32
	SortOrder                               int32
	CharacterBoardEffectType                int32
	CharacterBoardEffectId                  int32
	EffectValue                             int32
}

// EntityMCharacterBoardPanelReleasePossessionGroup is table key "m_character_board_panel_release_possession_group".
type EntityMCharacterBoardPanelReleasePossessionGroup struct {
	_                                           struct{} `msgpack:",array"`
	CharacterBoardPanelReleasePossessionGroupId int32
	PossessionType                              int32
	PossessionId                                int32
	Count                                       int32
	SortOrder                                   int32
}

// EntityMCharacterBoardStatusUp is table key "m_character_board_status_up".
type EntityMCharacterBoardStatusUp struct {
	_                                 struct{} `msgpack:",array"`
	CharacterBoardStatusUpId          int32
	CharacterBoardStatusUpType        int32
	CharacterBoardEffectTargetGroupId int32
}

// EntityMCharacterRebirth is table key "m_character_rebirth".
type EntityMCharacterRebirth struct {
	_                           struct{} `msgpack:",array"`
	CharacterId                 int32
	CharacterRebirthStepGroupId int32
	SortOrder                   int32
	CharacterAssignmentType     int32
}

// EntityMCharacterRebirthMaterialGroup is table key "m_character_rebirth_material_group".
type EntityMCharacterRebirthMaterialGroup struct {
	_                               struct{} `msgpack:",array"`
	CharacterRebirthMaterialGroupId int32
	MaterialId                      int32
	Count                           int32
	SortOrder                       int32
}

// EntityMCharacterRebirthStepGroup is table key "m_character_rebirth_step_group".
type EntityMCharacterRebirthStepGroup struct {
	_                               struct{} `msgpack:",array"`
	CharacterRebirthStepGroupId     int32
	BeforeRebirthCount              int32
	CostumeLevelLimitUp             int32
	CharacterRebirthMaterialGroupId int32
}

// EntityMCharacterViewerField is table key "m_character_viewer_field".
type EntityMCharacterViewerField struct {
	_                           struct{} `msgpack:",array"`
	CharacterViewerFieldId      int32
	ReleaseEvaluateConditionId  int32
	PublishDatetime             int64
	CharacterViewerFieldAssetId int32
	AssetBackgroundId           int32
	SortOrder                   int32
}

// EntityMCompanion is table key "m_companion".
type EntityMCompanion struct {
	_                             struct{} `msgpack:",array"`
	CompanionId                   int32
	AttributeType                 int32
	CompanionCategoryType         int32
	CompanionBaseStatusId         int32
	CompanionStatusCalculationId  int32
	SkillId                       int32
	CompanionAbilityGroupId       int32
	ActorId                       int32
	ActorSkeletonId               int32
	AssetVariationId              int32
	CharacterMoverBattleActorAiId int32
}

// EntityMCompanionCategory is table key "m_companion_category".
type EntityMCompanionCategory struct {
	_                                  struct{} `msgpack:",array"`
	CompanionCategoryType              int32
	EnhancementCostNumericalFunctionId int32
}

// EntityMCompanionEnhancementMaterial is table key "m_companion_enhancement_material".
type EntityMCompanionEnhancementMaterial struct {
	_                     struct{} `msgpack:",array"`
	CompanionCategoryType int32
	Level                 int32
	MaterialId            int32
	Count                 int32
	SortOrder             int32
}

// EntityMConfig is table key "m_config".
type EntityMConfig struct {
	_         struct{} `msgpack:",array"`
	ConfigKey string
	Value     string
}

// EntityMConsumableItem is table key "m_consumable_item".
type EntityMConsumableItem struct {
	_                    struct{} `msgpack:",array"`
	ConsumableItemId     int32
	ConsumableItemType   int32
	SortOrder            int32
	SellPrice            int32
	ConsumableItemTermId int32
	AssetName            string
	AssetCategoryId      int32
	AssetVariationId     int32
}

// EntityMCostume is table key "m_costume".
type EntityMCostume struct {
	_                                struct{} `msgpack:",array"`
	CostumeId                        int32
	CharacterId                      int32
	ActorId                          int32
	CostumeAssetCategoryType         int32
	ActorSkeletonId                  int32
	AssetVariationId                 int32
	SkillfulWeaponType               int32
	RarityType                       int32
	CostumeBaseStatusId              int32
	CostumeStatusCalculationId       int32
	CostumeLimitBreakMaterialGroupId int32
	CostumeAbilityGroupId            int32
	CostumeActiveSkillGroupId        int32
	CounterSkillDetailId             int32
	CharacterMoverBattleActorAiId    int32
	CostumeDefaultSkillGroupId       int32
	CostumeLevelBonusId              int32
	DefaultActorSkillAiId            int32
	CostumeEmblemAssetId             int32
	BattleActorSkillAiGroupId        int32
}

// EntityMCostumeActiveSkillEnhancementMaterial is table key "m_costume_active_skill_enhancement_material".
type EntityMCostumeActiveSkillEnhancementMaterial struct {
	_                                       struct{} `msgpack:",array"`
	CostumeActiveSkillEnhancementMaterialId int32
	SkillLevel                              int32
	MaterialId                              int32
	Count                                   int32
	SortOrder                               int32
}

// EntityMCostumeActiveSkillGroup is table key "m_costume_active_skill_group".
type EntityMCostumeActiveSkillGroup struct {
	_                                       struct{} `msgpack:",array"`
	CostumeActiveSkillGroupId               int32
	CostumeLimitBreakCountLowerLimit        int32
	CostumeActiveSkillId                    int32
	CostumeActiveSkillEnhancementMaterialId int32
}

// EntityMCostumeAwaken is table key "m_costume_awaken".
type EntityMCostumeAwaken struct {
	_                                struct{} `msgpack:",array"`
	CostumeId                        int32
	CostumeAwakenEffectGroupId       int32
	CostumeAwakenStepMaterialGroupId int32
	CostumeAwakenPriceGroupId        int32
}

// EntityMCostumeAwakenEffectGroup is table key "m_costume_awaken_effect_group".
type EntityMCostumeAwakenEffectGroup struct {
	_                          struct{} `msgpack:",array"`
	CostumeAwakenEffectGroupId int32
	AwakenStep                 int32
	CostumeAwakenEffectType    int32
	CostumeAwakenEffectId      int32
}

// EntityMCostumeAwakenItemAcquire is table key "m_costume_awaken_item_acquire".
type EntityMCostumeAwakenItemAcquire struct {
	_                          struct{} `msgpack:",array"`
	CostumeAwakenItemAcquireId int32
	PossessionType             int32
	PossessionId               int32
	Count                      int32
}

// EntityMCostumeAwakenPriceGroup is table key "m_costume_awaken_price_group".
type EntityMCostumeAwakenPriceGroup struct {
	_                         struct{} `msgpack:",array"`
	CostumeAwakenPriceGroupId int32
	AwakenStepLowerLimit      int32
	Gold                      int32
}

// EntityMCostumeAwakenStatusUpGroup is table key "m_costume_awaken_status_up_group".
type EntityMCostumeAwakenStatusUpGroup struct {
	_                            struct{} `msgpack:",array"`
	CostumeAwakenStatusUpGroupId int32
	SortOrder                    int32
	StatusKindType               int32
	StatusCalculationType        int32
	EffectValue                  int32
}

// EntityMCostumeDuplicationExchangePossessionGroup is table key "m_costume_duplication_exchange_possession_group".
type EntityMCostumeDuplicationExchangePossessionGroup struct {
	_              struct{} `msgpack:",array"`
	CostumeId      int32
	PossessionType int32
	PossessionId   int32
	Count          int32
}

// EntityMCostumeLimitBreakMaterialGroup is table key "m_costume_limit_break_material_group".
type EntityMCostumeLimitBreakMaterialGroup struct {
	_                                        struct{} `msgpack:",array"`
	CostumeLimitBreakMaterialGroupId         int32
	MaterialId                               int32
	Count                                    int32
	SortOrder                                int32
	CostumeOverflowExchangePossessionGroupId int32
}

// EntityMCostumeLotteryEffect is table key "m_costume_lottery_effect".
type EntityMCostumeLotteryEffect struct {
	_                                         struct{} `msgpack:",array"`
	CostumeId                                 int32
	SlotNumber                                int32
	CostumeLotteryEffectOddsGroupId           int32
	CostumeLotteryEffectUnlockMaterialGroupId int32
	CostumeLotteryEffectDrawMaterialGroupId   int32
	CostumeLotteryEffectReleaseScheduleId     int32
}

// EntityMCostumeLotteryEffectMaterialGroup is table key "m_costume_lottery_effect_material_group".
type EntityMCostumeLotteryEffectMaterialGroup struct {
	_                                   struct{} `msgpack:",array"`
	CostumeLotteryEffectMaterialGroupId int32
	MaterialId                          int32
	Count                               int32
	SortOrder                           int32
}

// EntityMCostumeLotteryEffectOddsGroup is table key "m_costume_lottery_effect_odds_group".
type EntityMCostumeLotteryEffectOddsGroup struct {
	_                               struct{} `msgpack:",array"`
	CostumeLotteryEffectOddsGroupId int32
	OddsNumber                      int32
	Weight                          int32
	CostumeLotteryEffectType        int32
	CostumeLotteryEffectTargetId    int32
	RarityType                      int32
}

// EntityMCostumeRarity is table key "m_costume_rarity".
type EntityMCostumeRarity struct {
	_                                             struct{} `msgpack:",array"`
	RarityType                                    int32
	CostumeLimitBreakMaterialRarityGroupId        int32
	EnhancementCostByMaterialNumericalFunctionId  int32
	LimitBreakCostNumericalFunctionId             int32
	MaxLevelNumericalFunctionId                   int32
	RequiredExpForLevelUpNumericalParameterMapId  int32
	ActiveSkillMaxLevelNumericalFunctionId        int32
	ActiveSkillEnhancementCostNumericalFunctionId int32
}

// EntityMEvaluateCondition is table key "m_evaluate_condition".
type EntityMEvaluateCondition struct {
	_                             struct{} `msgpack:",array"`
	EvaluateConditionId           int32
	EvaluateConditionFunctionType int32
	EvaluateConditionEvaluateType int32
	EvaluateConditionValueGroupId int32
	NameEvaluateConditionTextId   int32
}

// EntityMEvaluateConditionValueGroup is table key "m_evaluate_condition_value_group".
type EntityMEvaluateConditionValueGroup struct {
	_                             struct{} `msgpack:",array"`
	EvaluateConditionValueGroupId int32
	GroupIndex                    int32
	Value                         int64
}

// EntityMExplore is table key "m_explore".
type EntityMExplore struct {
	_                        struct{} `msgpack:",array"`
	ExploreId                int32
	ExploreUnlockConditionId int32
	StartDatetime            int64
	ConsumeItemCount         int32
	RewardLotteryCount       int32
}

// EntityMExploreGradeAsset is table key "m_explore_grade_asset".
type EntityMExploreGradeAsset struct {
	_                struct{} `msgpack:",array"`
	ExploreGradeId   int32
	AssetGradeIconId int32
}

// EntityMExploreGradeScore is table key "m_explore_grade_score".
type EntityMExploreGradeScore struct {
	_              struct{} `msgpack:",array"`
	ExploreId      int32
	NecessaryScore int32
	ExploreGradeId int32
}

// EntityMGachaMedal is table key "m_gacha_medal".
type EntityMGachaMedal struct {
	_                     struct{} `msgpack:",array"`
	GachaMedalId          int32
	CeilingCount          int32
	ConsumableItemId      int32
	ShopTransitionGachaId int32
	AutoConvertDatetime   int64
	ConversionRate        int32
}

// EntityMGimmickSequenceSchedule is table key "m_gimmick_sequence_schedule".
type EntityMGimmickSequenceSchedule struct {
	_                          struct{} `msgpack:",array"`
	GimmickSequenceScheduleId  int32
	StartDatetime              int64
	EndDatetime                int64
	FirstGimmickSequenceId     int32
	ReleaseEvaluateConditionId int32
}

// EntityMLoginBonusStamp is table key "m_login_bonus_stamp".
type EntityMLoginBonusStamp struct {
	_                    struct{} `msgpack:",array"`
	LoginBonusId         int32
	LowerPageNumber      int32
	StampNumber          int32
	RewardPossessionType int32
	RewardPossessionId   int32
	RewardCount          int32
}

// EntityMMainQuestChapter is table key "m_main_quest_chapter".
type EntityMMainQuestChapter struct {
	_                          struct{} `msgpack:",array"`
	MainQuestChapterId         int32
	MainQuestRouteId           int32
	SortOrder                  int32
	MainQuestSequenceGroupId   int32
	PortalCageCharacterGroupId int32
	StartDatetime              int64
	IsInvisibleInLibrary       bool
	JoinLibraryChapterId       int32
}

// EntityMMainQuestRoute is table key "m_main_quest_route".
type EntityMMainQuestRoute struct {
	_                 struct{} `msgpack:",array"`
	MainQuestRouteId  int32
	MainQuestSeasonId int32
	SortOrder         int32
	CharacterId       int32
}

// EntityMMainQuestSequence is table key "m_main_quest_sequence".
type EntityMMainQuestSequence struct {
	_                   struct{} `msgpack:",array"`
	MainQuestSequenceId int32
	SortOrder           int32
	QuestId             int32
}

// EntityMMaterial is table key "m_material".
type EntityMMaterial struct {
	_                              struct{} `msgpack:",array"`
	MaterialId                     int32
	MaterialType                   int32
	RarityType                     int32
	WeaponType                     int32
	AttributeType                  int32
	EffectValue                    int32
	SellPrice                      int32
	AssetName                      string
	AssetCategoryId                int32
	AssetVariationId               int32
	MaterialSaleObtainPossessionId int32
}

// EntityMMomBanner is table key "m_mom_banner".
type EntityMMomBanner struct {
	_                     struct{} `msgpack:",array"`
	MomBannerId           int32
	SortOrderDesc         int32
	DestinationDomainType int32
	DestinationDomainId   int32
	BannerAssetName       string
	IsEmphasis            bool
	StartDatetime         int64
	EndDatetime           int64
	TargetUserStatusType  int32
}

// EntityMNumericalFunction is table key "m_numerical_function".
type EntityMNumericalFunction struct {
	_                                 struct{} `msgpack:",array"`
	NumericalFunctionId               int32
	NumericalFunctionType             int32
	NumericalFunctionParameterGroupId int32
}

// EntityMNumericalFunctionParameterGroup is table key "m_numerical_function_parameter_group".
type EntityMNumericalFunctionParameterGroup struct {
	_                                 struct{} `msgpack:",array"`
	NumericalFunctionParameterGroupId int32
	ParameterIndex                    int32
	ParameterValue                    int32
}

// EntityMNumericalParameterMap is table key "m_numerical_parameter_map".
type EntityMNumericalParameterMap struct {
	_                       struct{} `msgpack:",array"`
	NumericalParameterMapId int32
	ParameterKey            int32
	ParameterValue          int32
}

// EntityMOmikuji is table key "m_omikuji".
type EntityMOmikuji struct {
	_              struct{} `msgpack:",array"`
	OmikujiId      int32
	StartDatetime  int64
	EndDatetime    int64
	OmikujiAssetId int32
}

// EntityMParts is table key "m_parts".
type EntityMParts struct {
	_                             struct{} `msgpack:",array"`
	PartsId                       int32
	RarityType                    int32
	PartsGroupId                  int32
	PartsStatusMainLotteryGroupId int32
	PartsStatusSubLotteryGroupId  int32
	PartsInitialLotteryId         int32
}

// EntityMPartsLevelUpPriceGroup is table key "m_parts_level_up_price_group".
type EntityMPartsLevelUpPriceGroup struct {
	_                        struct{} `msgpack:",array"`
	PartsLevelUpPriceGroupId int32
	LevelLowerLimit          int32
	Gold                     int32
}

// EntityMPartsLevelUpRateGroup is table key "m_parts_level_up_rate_group".
type EntityMPartsLevelUpRateGroup struct {
	_                       struct{} `msgpack:",array"`
	PartsLevelUpRateGroupId int32
	LevelLowerLimit         int32
	SuccessRatePermil       int32
}

// EntityMPartsRarity is table key "m_parts_rarity".
type EntityMPartsRarity struct {
	_                            struct{} `msgpack:",array"`
	RarityType                   int32
	PartsLevelUpRateGroupId      int32
	PartsLevelUpPriceGroupId     int32
	SellPriceNumericalFunctionId int32
}

// EntityMQuest is table key "m_quest".
type EntityMQuest struct {
	_                            struct{} `msgpack:",array"`
	QuestId                      int32
	NameQuestTextId              int32
	PictureBookNameQuestTextId   int32
	QuestReleaseConditionListId  int32
	StoryQuestTextId             int32
	QuestDisplayAttributeGroupId int32
	RecommendedDeckPower         int32
	QuestFirstClearRewardGroupId int32
	QuestPickupRewardGroupId     int32
	QuestDeckRestrictionGroupId  int32
	QuestMissionGroupId          int32
	Stamina                      int32
	UserExp                      int32
	CharacterExp                 int32
	CostumeExp                   int32
	Gold                         int32
	DailyClearableCount          int32
	IsRunInTheBackground         bool
	IsCountedAsQuest             bool
	QuestBonusId                 int32
	IsNotShowAfterClear          bool
	IsBigWinTarget               bool
	IsUsableSkipTicket           bool
	QuestReplayFlowRewardGroupId int32
	InvisibleQuestMissionGroupId int32
	FieldEffectGroupId           int32
}

// EntityMQuestFirstClearRewardGroup is table key "m_quest_first_clear_reward_group".
type EntityMQuestFirstClearRewardGroup struct {
	_                            struct{} `msgpack:",array"`
	QuestFirstClearRewardGroupId int32
	QuestFirstClearRewardType    int32
	SortOrder                    int32
	PossessionType               int32
	PossessionId                 int32
	Count                        int32
	IsPickup                     bool
}

// EntityMQuestFirstClearRewardSwitch is table key "m_quest_first_clear_reward_switch".
type EntityMQuestFirstClearRewardSwitch struct {
	_                            struct{} `msgpack:",array"`
	QuestId                      int32
	QuestFirstClearRewardGroupId int32
	SwitchConditionClearQuestId  int32
}

// EntityMQuestMission is table key "m_quest_mission".
type EntityMQuestMission struct {
	_                                 struct{} `msgpack:",array"`
	QuestMissionId                    int32
	QuestMissionConditionType         int32
	ConditionValue                    int32
	QuestMissionRewardId              int32
	QuestMissionConditionValueGroupId int32
}

// EntityMQuestMissionGroup is table key "m_quest_mission_group".
type EntityMQuestMissionGroup struct {
	_                   struct{} `msgpack:",array"`
	QuestMissionGroupId int32
	SortOrder           int32
	QuestMissionId      int32
}

// EntityMQuestMissionReward is table key "m_quest_mission_reward".
type EntityMQuestMissionReward struct {
	_                    struct{} `msgpack:",array"`
	QuestMissionRewardId int32
	PossessionType       int32
	PossessionId         int32
	Count                int32
}

// EntityMQuestPickupRewardGroup is table key "m_quest_pickup_reward_group".
type EntityMQuestPickupRewardGroup struct {
	_                        struct{} `msgpack:",array"`
	QuestPickupRewardGroupId int32
	SortOrder                int32
	BattleDropRewardId       int32
}

// EntityMQuestReplayFlowRewardGroup is table key "m_quest_replay_flow_reward_group".
type EntityMQuestReplayFlowRewardGroup struct {
	_                            struct{} `msgpack:",array"`
	QuestReplayFlowRewardGroupId int32
	SortOrder                    int32
	PossessionType               int32
	PossessionId                 int32
	Count                        int32
}

// EntityMQuestScene is table key "m_quest_scene".
type EntityMQuestScene struct {
	_                     struct{} `msgpack:",array"`
	QuestSceneId          int32
	QuestId               int32
	SortOrder             int32
	QuestSceneType        int32
	AssetBackgroundId     int32
	EventMapNumberUpper   int32
	EventMapNumberLower   int32
	IsMainFlowQuestTarget bool
	IsBattleOnlyTarget    bool
	QuestResultType       int32
	IsStorySkipTarget     bool
}

// EntityMQuestSceneBattle is table key "m_quest_scene_battle".
type EntityMQuestSceneBattle struct {
	_                             struct{} `msgpack:",array"`
	QuestSceneId                  int32
	BattleGroupId                 int32
	BattleDropBoxGroupId          int32
	BattleFieldLocaleSettingIndex int32
	BattleEventGroupId            int32
	PostProcessConfigurationIndex int32
}

// EntityMShop is table key "m_shop".
type EntityMShop struct {
	_                       struct{} `msgpack:",array"`
	ShopId                  int32
	ShopGroupType           int32
	SortOrderInShopGroup    int32
	ShopType                int32
	NameShopTextId          int32
	ShopUpdatableLabelType  int32
	ShopExchangeType        int32
	ShopItemCellGroupId     int32
	RelatedMainFunctionType int32
	StartDatetime           int64
	EndDatetime             int64
	LimitedOpenId           int32
}

// EntityMShopItem is table key "m_shop_item".
type EntityMShopItem struct {
	_                      struct{} `msgpack:",array"`
	ShopItemId             int32
	NameShopTextId         int32
	DescriptionShopTextId  int32
	ShopItemContentType    int32
	PriceType              int32
	PriceId                int32
	Price                  int32
	RegularPrice           int32
	ShopPromotionType      int32
	ShopItemLimitedStockId int32
	AssetCategoryId        int32
	AssetVariationId       int32
	ShopItemDecorationType int32
}

// EntityMShopItemCell is table key "m_shop_item_cell".
type EntityMShopItemCell struct {
	_              struct{} `msgpack:",array"`
	ShopItemCellId int32
	StepNumber     int32
	ShopItemId     int32
}

// EntityMShopItemCellGroup is table key "m_shop_item_cell_group".
type EntityMShopItemCellGroup struct {
	_                   struct{} `msgpack:",array"`
	ShopItemCellGroupId int32
	ShopItemCellId      int32
	SortOrder           int32
	ShopItemCellTermId  int32
}

// EntityMShopItemContentEffect is table key "m_shop_item_content_effect".
type EntityMShopItemContentEffect struct {
	_                struct{} `msgpack:",array"`
	ShopItemId       int32
	EffectTargetType int32
	EffectValueType  int32
	EffectValue      int32
}

// EntityMShopItemContentPossession is table key "m_shop_item_content_possession".
type EntityMShopItemContentPossession struct {
	_              struct{} `msgpack:",array"`
	ShopItemId     int32
	PossessionType int32
	PossessionId   int32
	SortOrder      int32
	Count          int32
}

// EntityMShopItemLimitedStock is table key "m_shop_item_limited_stock".
type EntityMShopItemLimitedStock struct {
	_                       struct{} `msgpack:",array"`
	ShopItemLimitedStockId  int32
	MaxCount                int32
	ShopItemAutoResetType   int32
	ShopItemAutoResetPeriod int32
}

// EntityMSideStoryQuestScene is table key "m_side_story_quest_scene".
type EntityMSideStoryQuestScene struct {
	_                     struct{} `msgpack:",array"`
	SideStoryQuestId      int32
	SideStoryQuestSceneId int32
	SortOrder             int32
	AssetBackgroundId     int32
	EventMapNumberUpper   int32
	EventMapNumberLower   int32
}

// EntityMTutorialUnlockCondition is table key "m_tutorial_unlock_condition".
type EntityMTutorialUnlockCondition struct {
	_                           struct{} `msgpack:",array"`
	TutorialType                int32
	TutorialUnlockConditionType int32
	ConditionValue              int32
}

// EntityMUserLevel is table key "m_user_level".
type EntityMUserLevel struct {
	_          struct{} `msgpack:",array"`
	UserLevel  int32
	MaxStamina int32
}

// EntityMUserQuestSceneGrantPossession is table key "m_user_quest_scene_grant_possession".
type EntityMUserQuestSceneGrantPossession struct {
	_              struct{} `msgpack:",array"`
	QuestSceneId   int32
	PossessionType int32
	PossessionId   int32
	Count          int32
	IsGift         bool
	IsDebug        bool
}

// EntityMWeapon is table key "m_weapon".
type EntityMWeapon struct {
	_                                       struct{} `msgpack:",array"`
	WeaponId                                int32
	WeaponCategoryType                      int32
	WeaponType                              int32
	AssetVariationId                        int32
	RarityType                              int32
	AttributeType                           int32
	IsRestrictDiscard                       bool
	WeaponBaseStatusId                      int32
	WeaponStatusCalculationId               int32
	WeaponSkillGroupId                      int32
	WeaponAbilityGroupId                    int32
	WeaponEvolutionMaterialGroupId          int32
	WeaponEvolutionGrantPossessionGroupId   int32
	WeaponStoryReleaseConditionGroupId      int32
	WeaponSpecificEnhanceId                 int32
	WeaponSpecificLimitBreakMaterialGroupId int32
	CharacterWalkaroundRangeType            int32
	IsRecyclable                            bool
}

// EntityMWeaponAbilityEnhancementMaterial is table key "m_weapon_ability_enhancement_material".
type EntityMWeaponAbilityEnhancementMaterial struct {
	_                                  struct{} `msgpack:",array"`
	WeaponAbilityEnhancementMaterialId int32
	AbilityLevel                       int32
	MaterialId                         int32
	Count                              int32
	SortOrder                          int32
}

// EntityMWeaponAbilityGroup is table key "m_weapon_ability_group".
type EntityMWeaponAbilityGroup struct {
	_                                  struct{} `msgpack:",array"`
	WeaponAbilityGroupId               int32
	SlotNumber                         int32
	AbilityId                          int32
	WeaponAbilityEnhancementMaterialId int32
}

// EntityMWeaponAwaken is table key "m_weapon_awaken".
type EntityMWeaponAwaken struct {
	_                           struct{} `msgpack:",array"`
	WeaponId                    int32
	WeaponAwakenEffectGroupId   int32
	WeaponAwakenMaterialGroupId int32
	ConsumeGold                 int32
	LevelLimitUp                int32
}

// EntityMWeaponAwakenMaterialGroup is table key "m_weapon_awaken_material_group".
type EntityMWeaponAwakenMaterialGroup struct {
	_                           struct{} `msgpack:",array"`
	WeaponAwakenMaterialGroupId int32
	MaterialId                  int32
	Count                       int32
	SortOrder                   int32
}

// EntityMWeaponConsumeExchangeConsumableItemGroup is table key "m_weapon_consume_exchange_consumable_item_group".
type EntityMWeaponConsumeExchangeConsumableItemGroup struct {
	_                struct{} `msgpack:",array"`
	WeaponId         int32
	ConsumableItemId int32
	Count            int32
}

// EntityMWeaponEvolutionGroup is table key "m_weapon_evolution_group".
type EntityMWeaponEvolutionGroup struct {
	_                      struct{} `msgpack:",array"`
	WeaponEvolutionGroupId int32
	EvolutionOrder         int32
	WeaponId               int32
}

// EntityMWeaponEvolutionMaterialGroup is table key "m_weapon_evolution_material_group".
type EntityMWeaponEvolutionMaterialGroup struct {
	_                              struct{} `msgpack:",array"`
	WeaponEvolutionMaterialGroupId int32
	MaterialId                     int32
	Count                          int32
	SortOrder                      int32
}

// EntityMWeaponRarity is table key "m_weapon_rarity".
type EntityMWeaponRarity struct {
	_                                            struct{} `msgpack:",array"`
	RarityType                                   int32
	BaseEnhancementObtainedExp                   int32
	SellPriceNumericalFunctionId                 int32
	MaxLevelNumericalFunctionId                  int32
	MaxSkillLevelNumericalFunctionId             int32
	MaxAbilityLevelNumericalFunctionId           int32
	RequiredExpForLevelUpNumericalParameterMapId int32
	EnhancementCostByWeaponNumericalFunctionId   int32
	EnhancementCostByMaterialNumericalFunctionId int32
	SkillEnhancementCostNumericalFunctionId      int32
	AbilityEnhancementCostNumericalFunctionId    int32
	LimitBreakCostByWeaponNumericalFunctionId    int32
	LimitBreakCostByMaterialNumericalFunctionId  int32
	EvolutionCostNumericalFunctionId             int32
}

// EntityMWeaponSkillEnhancementMaterial is table key "m_weapon_skill_enhancement_material".
type EntityMWeaponSkillEnhancementMaterial struct {
	_                                struct{} `msgpack:",array"`
	WeaponSkillEnhancementMaterialId int32
	SkillLevel                       int32
	MaterialId                       int32
	Count                            int32
	SortOrder                        int32
}

// EntityMWeaponSkillGroup is table key "m_weapon_skill_group".
type EntityMWeaponSkillGroup struct {
	_                                struct{} `msgpack:",array"`
	WeaponSkillGroupId               int32
	SlotNumber                       int32
	SkillId                          int32
	WeaponSkillEnhancementMaterialId int32
}

// EntityMWeaponSpecificEnhance is table key "m_weapon_specific_enhance".
type EntityMWeaponSpecificEnhance struct {
	_                                            struct{} `msgpack:",array"`
	WeaponSpecificEnhanceId                      int32
	BaseEnhancementObtainedExp                   int32
	SellPriceNumericalFunctionId                 int32
	MaxLevelNumericalFunctionId                  int32
	MaxSkillLevelNumericalFunctionId             int32
	MaxAbilityLevelNumericalFunctionId           int32
	RequiredExpForLevelUpNumericalParameterMapId int32
	EnhancementCostByWeaponNumericalFunctionId   int32
	EnhancementCostByMaterialNumericalFunctionId int32
	SkillEnhancementCostNumericalFunctionId      int32
	AbilityEnhancementCostNumericalFunctionId    int32
	LimitBreakCostByWeaponNumericalFunctionId    int32
	LimitBreakCostByMaterialNumericalFunctionId  int32
	EvolutionCostNumericalFunctionId             int32
}

// EntityMWeaponStoryReleaseConditionGroup is table key "m_weapon_story_release_condition_group".
type EntityMWeaponStoryReleaseConditionGroup struct {
	_                                           struct{} `msgpack:",array"`
	WeaponStoryReleaseConditionGroupId          int32
	StoryIndex                                  int32
	WeaponStoryReleaseConditionType             int32
	ConditionValue                              int32
	WeaponStoryReleaseConditionOperationGroupId int32
}
