services:
  server:
    build: .
    image: kretts/lunar-tear:latest
    environment:
      LUNAR_HOST: 127.0.0.1
      LUNAR_HTTP_PORT: 8080
      LUNAR_GRPC_PORT: 8003
    volumes:
      - ./assets:/opt/lunar-tear/assets
      - ./db:/opt/lunar-tear/db
    ports:
      - 8003:8003
      - 8080:8080

      