name: lunar-tear

services:
  server:
    build: .
    image: kretts/lunar-tear:latest
    restart: unless-stopped
    environment:
      LUNAR_LISTEN: 0.0.0.0:8003
      LUNAR_PUBLIC_ADDR: 127.0.0.1:8003
      LUNAR_OCTO_URL: http://cdn:8080
      LUNAR_AUTH_URL: http://auth:3000
    volumes:
      - ./db:/opt/lunar-tear/db
      - ./assets:/opt/lunar-tear/assets
    ports:
      - 8003:8003
    depends_on:
      - cdn
      - auth

  cdn:
    build:
      context: .
      dockerfile: Dockerfile.cdn
    image: kretts/octo-cdn:latest
    restart: unless-stopped
    command: ["--listen", "0.0.0.0:8080", "--public-addr", "10.0.2.2:8080"]
    volumes:
      - ./assets:/opt/octo-cdn/assets
    ports:
      - 8080:8080

  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    image: kretts/auth-server:latest
    restart: unless-stopped
    command: ["--listen", "0.0.0.0:3000", "--db", "db/auth.db"]
    volumes:
      - ./db:/opt/auth-server/db
    ports:
      - 3000:3000
